### ISSUE TITLE
With latest version I can't build

### ISSUE THREAD

**Issue by paul1956** [kirsan31/winforms-datavisualization#22]
I synced fork in my GitHub account
Deleted local folder
Cloned using VS
I get errors below

![image](https://user-images.githubusercontent.com/12789369/211231794-cf6dd0c5-5c8f-4c5a-9662-d21e30fa8866.png)

**Comment by kirsan31** [comment]
As I can understand the problem is that you have outdated nuget.exe in your PATH. But in theory, all libraries should be built normally. Only auto-restore in `DesignerTest` does not work after the build.

To get rid of these errors you can do one of the following:

1. Comment out this lines:
  https://github.com/kirsan31/winforms-datavisualization/blob/96ed59b82c0fdab0c401e84d0854e227eeb78ea2/src/WinForms.DataVisualization.Package/DataVisualization.Package.csproj#L77-L79
2. Update nuget.exe (that in your PATH) from here: https://www.nuget.org/downloads, direct link: https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

And I'll think, what to do... Add a note about needed of nuget.exe, or maybe I can remove it completely? The work of transferring the designer is already finished...

**Comment by paul1956** [comment]
Updated NuGet and it builds without errors.
